blog/urls.py
from django.urls import path
from .views import BlogView, ListBlogView

urlpatterns = [
    path('blogs/', ListBlogView.as_view(), name='list_blog'),
    path('blog/<int:pk>/', BlogView.as_view(), name='detail_blog'),

]

blog_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [

    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html')),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import HomePageView, UsersListView



urlpatterns = [
    path('users/', UsersListView.as_view(template_name='users/users_list.html'), name='users_list'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('home/', HomePageView.as_view(), name='home'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from users.models import User


class Blog(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец блога')
    blog_id = models.AutoField(primary_key=True)

    def __str__(self):
        return str(self.owner)

    def get_absolute_url(self):
        return reverse('detail_blog', args=[self.pk])

    class Meta:
        verbose_name = 'Блог пользователя'
        verbose_name_plural = 'Блоги пользователей'


class New(models.Model):
    user_blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Блог', blank=False, null=False,
                                  related_name='news')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', blank=False,
                               null=False)
    title = models.CharField(max_length=150, verbose_name='Название')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    news_text = models.TextField(max_length=600, blank=True, verbose_name='Текст')

    def __str__(self):
        return str(self.author)

    class Meta:
        verbose_name = 'Новость блога'
        verbose_name_plural = 'Новости блога'
        ordering = ['-created_at']


class Subscription(models.Model):
    subscription_no = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_id = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ['subscription_no']
        unique_together = ('blog_id', 'user_id')

    def get_absolute_url(self):
        return reverse('list_blog')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True, blank=False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name = 'Блогер'
        verbose_name_plural = 'Блогеры'

blog/forms.py
from django import forms
from django.forms import Textarea
from .models import New, Subscription


class CreateSubForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = "__all__"


class CreateNewsForm(forms.ModelForm):
    class Meta:
        model = New
        fields = ('title', 'news_text')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['news_text'].widget = Textarea(attrs={'rows': 5})

blog/views.py
from urllib import request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin
from blog.forms import CreateNewsForm, CreateSubForm
from blog.models import Blog


class ListBlogView(LoginRequiredMixin, ListView):
    model = Blog
    template_name = 'blog/blog_list.html'


class BlogView(FormMixin, DetailView):
    model = Blog
    template_name = 'blog/detail_blog.html'
    form_class = CreateNewsForm

    def get_success_url(self, **kwargs):
        return reverse_lazy('detail_blog', kwargs={'pk': self.get_object().pk})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_blog = self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class SubscribeView(FormMixin, ListView):
    form_class = CreateSubForm
    model = Blog
    success_url = reverse_lazy('list_blog')
    template_name = 'blog/detail_blog.html'

    def form_valid(self, form):
        return super().form_valid(form)

users/views.py
from django.views.generic import TemplateView, ListView
from users.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class HomePageView(TemplateView):
    template_name = 'home.html'


class UsersListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name = 'users/users_list.html'

    def test_func(self):
        if self.request.user.is_authenticated:
            return True
        return False

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <title>{% block title %} Блоги для блогеров {% endblock title %}</title>
</head>

<body style="background-color: gray" text="white">

<div class="container md-3 center">
    {% if user.is_authenticated %}


    <div class="container" style="background-color: white">
         <div class="container">

         <h5>Вы авторизированы как, {{user.username}}
        <a href="{% url 'home' %}" style="background-color: white">
            На главную</a>||<a href="{% url 'logout' %}" style="background-color: white">
            Выйти</a></h5></div>


    {% else %}
    <h1>:)</h1>
    {%endif%}
        <div class="container-md-3 ">
            <div class="bg-dark text-white">

                {% block content %}

                {% endblock content %}
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAKl8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %}Блоги{% endblock title %}

{% block content %}

{% if user.is_authenticated %}

<h3 class="text-md-center">Список блогов:</h3>

{% for blog in blog_list %}
<div class="main-container">

    <div id="layer2" class="container-p-3">
        <div class="card">
            <div class="card-body-md-center">
                <button class="info nullbutton">
                    <a href="{% url 'detail_blog' blog.pk %}">
                        <font color="black">Блог блогера <font>
                            <b>{{ blog.owner }}</b>
                        </font></font>
                    </a>
                </button>
            </div>
            <button class="info nullbutton">
                <a href="{% url 'detail_blog' blog.pk %}" class="btn bg-dark text-white">Смотреть полностью</a>
            </button>
            {% if user.is_authenticated and request.user.pk != blog.owner.pk %}

                {%if request.user != blog.user_id %}

                <a href="{% url 'list_blog' blog.owner.pk %}" class="btn bg-dark text-white">Подписаться</a>
{% endif %}
            {% endif %}
        </div>
    </div>
</div>
<hr>

{% endfor %}

{% endif %}

{% endblock content %}

templates/blog/detail_blog.html
{% extends 'base.html' %}


{% block content %}

    <div class="card text-center" style=" background-image:
     url('https://images.wallpaperscraft.ru/image/nochnoj_gorod_ogni_goroda_megapolis_126569_1600x900.jpg');">

        <div class="card-header">
            <h2 class="card-title">Блог блогера, {{ blog }}</h2>
        </div>

    <div class="comment">
        <hr color="white">
        <h3 align="center">Новости Блога</h3>
        <hr color="white">



    </div>

         {% if user.is_authenticated and request.user.pk == blog.owner.pk %}
    <div class="container-md-center" style="background-color: #16181b">

        <div class="col-lg-5" >
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" value="Добавить" class="btn btn-dark">Добавить</button>


            </form>
        </div>
            </div>
 {% endif %}
        <div class="container m-3">
       <p><input class="btn btn-dark" type="button" value="Назад к блогам"
                onclick="location.href='{% url 'list_blog' %}'"></p>
        </div>
    </div>

        <div class="container">
            {% for i in  blog.news.all %}
            <hr color="white">
        <div style="background-color: #16181b" class="col">
            <h5> Название: <font color="red">{{i.title}}</font></h5>
            <h5>Содержание: <font color="red">{{ i.news_text }}</font></h5>
            <p>Автор: <font color="red">{{ i.author }}.</font></p>
            <p>Опубликовано: <font color="red">{{ i.created_at }}</font> </p>
        </div>
            {% endfor %}
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}


<input class="btn-dark" type="button" value="Смотреть блогеров" onclick="location.href='{% url 'users_list' %}'">




{% else %}
<h3>Войдите в аккаунт!</h3>
<input class="btn-dark" type="button" value="Войти" onclick="location.href='{% url 'login' %}'">

{% endif %}

{% endblock content %}

templates/users/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}


    <style>

        table {
            width: 1500px; /* Ширина таблицы */
            margin: auto; /* Выравниваем таблицу по центру */
        }

        td, th {
            border: 2px solid green; /* Рамка вокруг таблицы */
            text-align: center; /* Выравниваем текст по центру ячейки */
        }
        input.btn.btn-dark {
 float: right;
}
input.btn-dark {
 float: top;
}
    </style>


    <h3 class="text-md-center">Список зарегистрированных пользователей:</h3>

<div class="main-container">


    <form>
        {% csrf_token %}

        <div class="table-responsive-lg">
            <table class="table table-hover table-dark" style="background-color: #16181b ">
                <thead>
                <tr>

                    <th scope="col">Никнэйм</th>
                    <th scope="col">Электронная почта</th>

                    <th scope="col">Блог</th>

                </tr>
                {% for user in customuser_list %}

                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>


                        <td><input class="btn-dark" type="button" value="Читать блог" onclick="location.href='#'"></td>

                    </tr>

                {% endfor %}

                </thead>

            </table>


        </div>

    </form>


</div>



{% else %}
<h3>Войдите в аккаунт или зарегистрируйтесь!</h3>


{% endif %}

{% endblock content %}

templates/users/users_list.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}

<style>

    table {
        width: 1500px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру */
    }

    td, th {
        border: 2px solid green; /* Рамка вокруг таблицы */
        text-align: center; /* Выравниваем текст по центру ячейки */
    }

    input.btn.btn-dark {
        float: right;
    }

    input.btn-dark {
        float: top;
    }
</style>


<h3 class="text-md-center">Список всех блогеров:</h3>

<div class="main-container">


    <form>
        {% csrf_token %}

        <div class="table-responsive-lg">
            <table class="table table-hover table-dark" style="background-color: cornflowerblue ">
                <thead>
                <tr>

                    <th scope="col">Блогер</th>
                    <th scope="col">Электронная почта</th>

                </tr>
                {% for user in user_list %}
                <tr>
                    <td>
                        <a href="{% url 'detail_blog' user.pk %}">
                            <font color="black"><b>{{ user.username }}</b></font>
                        </a>
                    </td>

                    <td>{{ user.email }}</td>

                </tr>


                {% endfor %}


                </thead>

            </table>
            <input class="btn-dark" type="button" value="Смотреть все блоги"
                   onclick="location.href='{% url 'list_blog' %}'">

        </div>

    </form>


</div>

{% endif %}

{% endblock content %}